// ─── KiTee Studio — Product Catalogue ───────────────────────────────────────
// Prices are stored in GBP in Supabase/admin — not hardcoded here.
// priceId comes from Stripe via env vars (still needed for checkout).
// productType: 'template' | 'app'
// appCategory: SEO-friendly category slugs for utility apps

export type ProductType = 'template' | 'app';

export type AppCategory =
  | 'adhd-neurodivergent'
  | 'fitness-wellness'
  | 'productivity-daily-life'
  | 'business-tools'
  | 'life-planning';

export type TemplateCategory =
  | 'coaches'
  | 'authors'
  | 'fitness'
  | 'podcasters'
  | 'freelancers'
  | 'shops'
  | 'speakers'
  | 'virtual-assistants';

export type Category = 'all' | 'templates' | 'apps' | AppCategory | TemplateCategory;

export type Product = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  description: string;
  price: number;           // GBP — source of truth, used as fallback
  priceId: string;         // Stripe price ID
  productType: ProductType;
  category: TemplateCategory | AppCategory;
  categoryLabel: string;
  categorySlug: AppCategory | TemplateCategory;
  features: string[];
  badge?: string;
  status: 'live' | 'coming-soon';
  image: string;
  mockupCount?: number;
  seoTitle?: string;
  seoDescription?: string;
};

// ─── Template categories ─────────────────────────────────────────────────────
export const TEMPLATE_CATEGORIES: { id: TemplateCategory; label: string }[] = [
  { id: 'coaches',     label: 'Coaches' },
  { id: 'authors',     label: 'Authors' },
  { id: 'fitness',     label: 'Fitness' },
  { id: 'podcasters',  label: 'Podcasters' },
  { id: 'freelancers', label: 'Freelancers' },
  { id: 'shops',       label: 'Shops' },
  { id: 'speakers',    label: 'Speakers' },
  { id: 'virtual-assistants', label: 'Virtual Assistants' },
];

// ─── App categories ───────────────────────────────────────────────────────────
export const APP_CATEGORIES: { id: AppCategory; label: string; description: string }[] = [
  {
    id: 'adhd-neurodivergent',
    label: 'AuDHD & Neurodivergent',
    description: 'Tools designed for neurodivergent brains — built by one.',
  },
  {
    id: 'fitness-wellness',
    label: 'Fitness & Wellness',
    description: 'Track your training, your body, your recovery.',
  },
  {
    id: 'productivity-daily-life',
    label: 'Productivity & Daily Life',
    description: 'Practical tools for the day-to-day stuff that needs to just work.',
  },
  {
    id: 'business-tools',
    label: 'Business Tools',
    description: 'Run the business side of your business, without the spreadsheet.',
  },
  {
    id: 'life-planning',
    label: 'Life Planning',
    description: 'Full-scope planners for the parts of life that need more than one page.',
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const PRODUCTS: Product[] = [

  // ── UTILITY APPS ──────────────────────────────────────────────────────────

  {
    id: 'burnout-recovery-blueprint',
    slug: 'burnout-recovery-blueprint',
    name: 'Burnout Recovery Blueprint',
    tagline: 'Track your energy. Map your recovery. Build back properly.',
    description: 'A self-contained offline app for tracking where your energy actually goes and building a real recovery plan — not a mood board. Built for brains that crash hard and need structure, not inspiration.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_BURNOUT || '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'live',
    image: '/images/products/burnout-01.jpg',
    features: [
      'Energy tracking across all life areas',
      'Burnout stage identifier',
      'Personalised recovery roadmap',
      'Daily check-in journal',
      'Works fully offline — no internet needed',
      'Download once, yours forever',
    ],
    seoTitle: 'Burnout Recovery App for AuDHD & Neurodivergent People',
    seoDescription: 'A downloadable offline app to track burnout, map your energy, and build a real recovery plan. Built for AuDHD and neurodivergent brains.',
  },

  {
    id: 'post-diagnosis-rebuild-kit',
    slug: 'post-diagnosis-rebuild-kit',
    name: 'Post-Diagnosis Rebuild Kit',
    tagline: 'Process your diagnosis. Rebuild a life that actually fits your brain.',
    description: 'Everything you need after a late AuDHD diagnosis — a guided app to process the grief, reclaim your identity, and start building life on your own terms. No toxic positivity. Just tools.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_REBUILD || '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'live',
    image: '/images/products/rebuild-01.jpg',
    features: [
      'Identity explorer with masked trait mapping',
      'Grief processor with guided prompts',
      'Weekly reflection journal',
      'Progress tracking',
      'Voice-to-text on all input fields',
      'Export your data anytime',
    ],
    seoTitle: 'Late ADHD Diagnosis App — Post-Diagnosis Rebuild Kit',
    seoDescription: 'A downloadable app for processing a late AuDHD diagnosis. Guided tools for identity, grief, and rebuilding — offline, no subscription.',
  },

  {
    id: 'unmasking-roadmap',
    slug: 'unmasking-roadmap',
    name: 'Unmasking Roadmap',
    tagline: 'Identify where you mask. Build a safer way to show up.',
    description: 'A guided tool for understanding your masking patterns and gradually building a more authentic way of being — at work, in relationships, and with yourself.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'coming-soon',
    image: '/images/products/unmasking-01.jpg',
    features: [],
    seoTitle: 'AuDHD Unmasking App — Unmasking Roadmap',
    seoDescription: 'A downloadable tool for neurodivergent people to identify masking patterns and build a more authentic way of showing up.',
  },

  {
    id: 'adhd-relationships-playbook',
    slug: 'adhd-relationships-playbook',
    name: 'AuDHD Relationships Playbook',
    tagline: 'Navigate connection with a neurodivergent brain — yours or theirs.',
    description: 'Tools for communication, conflict, and connection when AuDHD is part of the picture. Whether you\'re the neurodivergent one or you love someone who is.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'coming-soon',
    image: '/images/products/relationships-01.jpg',
    features: [],
    seoTitle: 'AuDHD Relationships App — Communication & Connection Tools',
    seoDescription: 'A downloadable app for navigating relationships with AuDHD. Tools for communication, conflict, and connection.',
  },

  {
    id: 'gym-tracker',
    slug: 'gym-tracker',
    name: 'Gym Tracker',
    tagline: 'Log your lifts. Track your progress. No subscription required.',
    description: 'A self-contained offline gym tracking app. Log sets, weights, reps, and track your progress over time — without a fitness app subscription. Download once, open in any browser, use forever.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_GYM || '',
    productType: 'app',
    category: 'fitness-wellness',
    categoryLabel: 'Fitness & Wellness',
    categorySlug: 'fitness-wellness',
    status: 'live',
    image: '/images/products/gym-01.jpg',
    features: [
      'Log sets, reps, and weights',
      'Workout history and progress tracking',
      'Custom exercise library',
      'Personal records tracker',
      'Works fully offline',
      'Download once, yours forever',
    ],
    seoTitle: 'Offline Gym Tracker App — No Subscription Workout Log',
    seoDescription: 'A downloadable offline gym tracker. Log workouts, track progress, and see your personal records — no subscription, no account, no internet needed.',
  },

  {
    id: 'the-executer',
    slug: 'the-executer',
    name: 'The Executer',
    tagline: 'Bypass task paralysis in seconds. No app download needed.',
    description: 'You pick what kind of stuck you are — brain too loud, body like lead, world too grating, target blurry, thought spiral, wall of dread — and The Executer triages your state into a guided rescue sequence instead of just handing you a to-do list.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'coming-soon',
    image: '/images/products/the-executer-01.jpg',
    features: [
      'Six stuck-state triage paths',
      'Guided breathing animation',
      'Step-by-step action prompts with a focus timer',
      'Progress tracking dots and a completion screen',
      'Works fully offline',
      'Download once, yours forever',
    ],
    seoTitle: 'The Executer — ADHD Executive Dysfunction & Task Paralysis Tool',
    seoDescription: 'A downloadable app that triages executive dysfunction and task paralysis into a personalised, regulation-first rescue sequence. Offline, no subscription.',
  },

  {
    id: 'heat-wave-survival-trilogy',
    slug: 'heat-wave-survival-trilogy',
    name: 'Heat Wave Survival Trilogy',
    tagline: 'Three offline apps for three different heat-overload moments.',
    description: 'Heat doesn\'t just make you hot — it makes you a different person. Heat Fog Survival Kit (guided cooling breaks + fog check), Heat Sleep Reset (wind-down routine + breathing pacer), and Heat Shutdown Shield (warning-sign checklist + de-escalation protocol), bundled in one download.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'coming-soon',
    image: '/images/products/heat-wave-survival-trilogy-01.jpg',
    features: [
      'Heat Fog Survival Kit — guided cooling break + fog check',
      'Heat Sleep Reset — wind-down routine + breathing pacer',
      'Heat Shutdown Shield — warning signs + reset protocol',
      'Voice journal on all three apps',
      'Everything runs locally — nothing leaves your device',
      'Three self-contained HTML files, open and use forever',
    ],
    seoTitle: 'Heat Wave Survival Trilogy — 3 AuDHD Heat-Coping Apps',
    seoDescription: 'Three offline apps for heat-triggered brain fog, sleepless nights, and shutdown risk. Bundle download, no subscription, private by design.',
  },

  {
    id: 'author-launch-kit',
    slug: 'author-launch-kit',
    name: 'Author Launch Kit',
    tagline: 'Track your launch. Track your royalties. All in one place.',
    description: 'A book launch tracker and royalty & income tracker in one self-contained app, built for authors juggling release timelines and money across multiple platforms without a spreadsheet held together with hope.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/author-launch-kit-01.jpg',
    features: [
      'Book launch tracker with milestones',
      'Royalty & income tracker across platforms',
      'Works fully offline',
      'No account, no subscription',
      'Download once, yours forever',
    ],
    seoTitle: 'Author Launch Kit — Book Launch & Royalty Tracker',
    seoDescription: 'A downloadable app for authors to track a book launch and royalty income in one place. Offline, no subscription, no spreadsheet required.',
  },

  {
    id: 'cleaning-starter-kit',
    slug: 'cleaning-business-starter-kit',
    name: 'Cleaning Business Starter Kit',
    tagline: 'Quote jobs. Track jobs. Run the business side without the spreadsheet.',
    description: 'A job tracker, client list, and quote calculator built for solo and small cleaning businesses — everything you need to go from enquiry to invoice without juggling three different apps.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/cleaning-business-starter-kit-01.jpg',
    features: [
      'Job tracker and setup checklist',
      'Client list',
      'Quote calculator',
      'Works fully offline',
      'Download once, yours forever',
    ],
    seoTitle: 'Cleaning Business Starter Kit — Job Tracker & Quote Calculator',
    seoDescription: 'A downloadable app for cleaning businesses to track jobs, clients, and quotes in one place. Offline, no subscription.',
  },

  {
    id: 'home-maintenance-tracker',
    slug: 'home-maintenance-tracker',
    name: 'Home Maintenance Tracker',
    tagline: 'Track every repair, appliance, and landlord conversation in one place.',
    description: 'An offline app for renters, homeowners, and landlords — log repair costs with photo evidence, track appliances and warranties, and generate a ready-to-send landlord email in one tap. Built for deposit disputes and reimbursement claims that need proof, not memory.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/home-maintenance-tracker-01.jpg',
    features: [
      'Repair cost tracking with automatic totals',
      'Photo evidence attached to each task',
      'One-tap Email Landlord generator',
      'Appliance & warranty tracking',
      'Full backup & restore as JSON',
      'Works fully offline',
    ],
    seoTitle: 'Home Maintenance Tracker App — Renter & Landlord Repair Log',
    seoDescription: 'A downloadable offline app to track home repairs, appliances, and warranties, with photo evidence and a one-tap landlord email generator.',
  },

  {
    id: 'debt-payoff-guide-tracker',
    slug: 'debt-payoff-guide-tracker',
    name: 'Debt Payoff Guide & Tracker',
    tagline: 'See exactly when you\'ll be debt-free, and watch the progress add up.',
    description: 'A debt tracker with a real amortisation schedule — log every debt, watch your progress bar move, and see the actual payoff date instead of guessing. Built for snowball and avalanche strategies alike.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/debt-payoff-guide-tracker-01.jpg',
    features: [
      'Multi-debt tracker grid',
      'Progress tracking toward payoff',
      'Amortisation schedule',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Debt Payoff Guide & Tracker — Snowball & Avalanche Planner',
    seoDescription: 'A downloadable debt payoff tracker with a real amortisation schedule and progress tracking. Offline, no subscription.',
  },

  {
    id: 'mindful-money-manager',
    slug: 'mindful-money-manager',
    name: 'Mindful Money Manager',
    tagline: 'Notice your spending patterns before they notice you.',
    description: 'A budgeting app built around a pause practice — a moment of friction before you spend — plus pattern tracking that shows you where your money actually goes, and a journal for the feelings underneath the numbers.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/mindful-money-manager-01.jpg',
    features: [
      'Pause practice before spending',
      'Budget tracker',
      'Spending pattern insights',
      'Money journal',
      'Works fully offline',
    ],
    seoTitle: 'Mindful Money Manager — Budget & Spending Pattern App',
    seoDescription: 'A downloadable budgeting app with a pause practice, spending pattern insights, and a money journal. Offline, no subscription.',
  },

  {
    id: 'the-whole-picture',
    slug: 'the-whole-picture',
    name: 'The Whole Picture',
    tagline: 'Your spending, your bills, and your budget — actually in one view.',
    description: 'A budgeting app that shows your spending breakdown for the month, what bills are coming due, and a weekly check-in to keep you honest — with full import and export so your data is never locked in.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/the-whole-picture-01.jpg',
    features: [
      'Spending breakdown by month',
      'Bills due tracker',
      'Weekly check-in with history',
      'Import and export your data',
      'Works fully offline',
    ],
    seoTitle: 'The Whole Picture — Budget, Bills & Weekly Check-In App',
    seoDescription: 'A downloadable budgeting app with a monthly spending breakdown, bills tracker, and weekly check-ins. Offline, no subscription.',
  },

  {
    id: 'timetrue',
    slug: 'timetrue',
    name: 'TimeTrue',
    tagline: 'Build in the buffer time your brain actually needs.',
    description: 'A time-management app built around the buffer method — realistic padding around tasks instead of optimistic back-to-back planning — plus a voice braindump for capturing everything in your head and a punctuality tracker that shows the pattern, not just the excuse.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/timetrue-01.jpg',
    features: [
      'Buffer method scheduling',
      'Voice braindump capture',
      'Punctuality tracking',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'TimeTrue — Buffer-Time Scheduling & Punctuality Tracker',
    seoDescription: 'A downloadable time-management app built around realistic buffer time, voice braindump capture, and punctuality tracking. Offline, no subscription.',
  },

  {
    id: 'writers-block-focus-timer',
    slug: 'writers-block-focus-timer',
    name: 'Writers-Block Focus Timer',
    tagline: 'A focus timer built for the blank page, not the boardroom.',
    description: 'A single-purpose focus timer for writers stuck at the blank page — built to get you into a session and keep you there, without the generic productivity-app noise.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/writers-block-focus-timer-01.jpg',
    features: [
      'Focused writing timer sessions',
      'Built for the blank-page moment',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Writers-Block Focus Timer — A Focus Timer for Writers',
    seoDescription: 'A downloadable focus timer app built for writers. Offline, no subscription, no distractions.',
  },

  {
    id: 'content-calendar-generator',
    slug: 'content-calendar-generator',
    name: 'Content Calendar Generator',
    tagline: 'Turn a handful of content pillars into a real posting plan.',
    description: 'Set your content pillars, run them through the generator, and get an actual tracked output plan — built for creators who know what they want to talk about but not when.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/content-calendar-generator-01.jpg',
    features: [
      'Content pillar setup',
      'Calendar generation engine',
      'Output tracking',
      'Works fully offline',
    ],
    seoTitle: 'Content Calendar Generator — Content Pillar Planning App',
    seoDescription: 'A downloadable app that turns content pillars into a tracked posting calendar. Offline, no subscription.',
  },

  {
    id: 'plate-quest',
    slug: 'plate-quest',
    name: 'Plate Quest',
    tagline: 'Turn eating well into a game you actually want to play.',
    description: 'A gamified food diary — log meals, complete quests, earn badges, and journal how food actually makes you feel, without a calorie count or a diet-culture undertone in sight.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'fitness-wellness',
    categoryLabel: 'Fitness & Wellness',
    categorySlug: 'fitness-wellness',
    status: 'coming-soon',
    image: '/images/products/plate-quest-01.jpg',
    features: [
      'Gamified food diary',
      'Quests and badges',
      'Reflection journal',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Plate Quest — Gamified Food Diary App',
    seoDescription: 'A downloadable gamified food diary with quests, badges, and a reflection journal. Offline, no subscription, no diet-culture noise.',
  },

  {
    id: 'wedding-week-planner',
    slug: 'wedding-week-planner',
    name: 'Wedding Week Planner',
    tagline: 'Every task, every timing, every person — for the week that matters.',
    description: 'A day-by-day planner for wedding week itself — task lists, an hour-by-hour day schedule, a wedding party contact list, and a place to keep your vows, all in one offline app.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/wedding-week-planner-01.jpg',
    features: [
      'Week-by-week task lists',
      'Hour-by-hour day schedule',
      'Wedding party contact list',
      'Vows storage',
      'Works fully offline',
    ],
    seoTitle: 'Wedding Week Planner — Day-By-Day Wedding Planning App',
    seoDescription: 'A downloadable wedding week planner with task lists, a day schedule, wedding party contacts, and vows storage. Offline, no subscription.',
  },

  {
    id: 'hen-shower-planner',
    slug: 'hen-shower-planner',
    name: 'Hen & Shower Planner',
    tagline: 'Guest list, schedule, activities, and budget — sorted.',
    description: 'A planner for hen dos and showers alike — guest list, run-of-show schedule, activity ideas, and a budget tracker, so the person planning it isn\'t the one losing the plot.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/hen-shower-planner-01.jpg',
    features: [
      'Guest list',
      'Run-of-show schedule',
      'Activity ideas',
      'Budget tracker',
      'Works fully offline',
    ],
    seoTitle: 'Hen & Shower Planner — Guest List, Schedule & Budget App',
    seoDescription: 'A downloadable planner for hen dos and showers with a guest list, schedule, activity ideas, and budget tracker. Offline, no subscription.',
  },

  {
    id: 'clientflow-tracker',
    slug: 'clientflow-tracker',
    name: 'Clientflow — Client & Project Tracker',
    tagline: 'Every client, every project, every invoice — in one offline board.',
    description: 'A Kanban-style client and project tracker for solo service businesses, with invoicing, a dashboard, and support for 40 global currencies. No login, no subscription — your data stays on your device.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/clientflow-tracker-01.jpg',
    features: [
      'Kanban project board',
      'Client management',
      'Invoicing with outstanding-total tracking',
      'Dashboard with charts',
      '40 global currencies supported',
      'Works fully offline',
    ],
    seoTitle: 'Clientflow — Offline Client & Project Tracker for Freelancers',
    seoDescription: 'A downloadable Kanban-style client and project tracker with invoicing and a dashboard. Offline-first, no login, no subscription.',
  },

  {
    id: 'clientflow-tandem',
    slug: 'clientflow-tandem',
    name: 'Clientflow Tandem',
    tagline: 'Clientflow, plus a Focus Room for body-doubling your way through the list.',
    description: 'Everything in Clientflow — Kanban board, invoicing, dashboard — plus a built-in Focus Room for body-doubling sessions when the client work needs company to actually get done.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/clientflow-tandem-01.jpg',
    badge: 'Premium',
    features: [
      'Everything in Clientflow Tracker',
      'Focus Room for body-doubling sessions',
      'Kanban project board & invoicing',
      '40 global currencies supported',
      'Works fully offline',
    ],
    seoTitle: 'Clientflow Tandem — Client Tracker with a Focus Room',
    seoDescription: 'A downloadable client and project tracker with invoicing, a dashboard, and a built-in Focus Room for body-doubling. Offline, no subscription.',
  },

  {
    id: 'postplanned',
    slug: 'postplanned',
    name: 'PostPlanned',
    tagline: 'Plan, queue, and track your content without living inside a scheduler subscription.',
    description: 'A full social media content calendar — month and week views, a post editor, a drag-to-queue workflow, a media vault, and real analytics — running entirely offline in your browser.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/postplanned-01.jpg',
    features: [
      'Month and week calendar views',
      'Post editor with drag-to-queue',
      'Media vault',
      'Analytics dashboard',
      'Works fully offline',
    ],
    seoTitle: 'PostPlanned — Offline Social Media Content Calendar',
    seoDescription: 'A downloadable social media content calendar with a post editor, media vault, and analytics. Offline, no subscription.',
  },

  {
    id: 'the-grounding-board',
    slug: 'the-grounding-board',
    name: 'The Grounding Board',
    tagline: 'A regulation utility for when you need to come back to your body.',
    description: 'A fast, focused AuDHD regulation tool — grounding exercises and sensory check-ins built for the moment things start to feel like too much, not for browsing later.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'coming-soon',
    image: '/images/products/grounding-board-01.jpg',
    features: [
      'Guided grounding exercises',
      'Sensory check-in',
      'Built for in-the-moment use',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'The Grounding Board — AuDHD Regulation Utility',
    seoDescription: 'A downloadable AuDHD grounding and regulation tool for in-the-moment overwhelm. Offline, no subscription.',
  },

  {
    id: 'audhd-week-reset',
    slug: 'audhd-week-reset-system',
    name: 'AuDHD Week Reset System',
    tagline: 'When the week has gotten away from you, this is how you reset it.',
    description: 'A structured weekly reset system for AuDHD brains — built for the Sunday-night (or Wednesday-afternoon) moment when everything feels behind and you need a real way back in, not another blank planner page.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'coming-soon',
    image: '/images/products/audhd-week-reset-01.jpg',
    features: [
      'Structured weekly reset flow',
      'Built for AuDHD overwhelm patterns',
      'Works fully offline',
      'Download once, yours forever',
    ],
    seoTitle: 'AuDHD Week Reset System — Weekly Reset App',
    seoDescription: 'A downloadable weekly reset system built for AuDHD brains. Offline, no subscription.',
  },

  {
    id: 'social-battery-calculator',
    slug: 'social-battery-calculator',
    name: 'Social Battery Calculator',
    tagline: 'Know your charge before you say yes to another thing.',
    description: 'A simple calculator for tracking your social battery — log what drains you, what recharges you, and get an honest read on whether you actually have the capacity for that plan.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'coming-soon',
    image: '/images/products/social-battery-01.jpg',
    features: [
      'Social battery tracking',
      'Drain and recharge logging',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Social Battery Calculator — Track Your Social Capacity',
    seoDescription: 'A downloadable social battery tracker for neurodivergent brains. Offline, no subscription.',
  },

  {
    id: 'focus-guardian',
    slug: 'body-double-focus-guardian',
    name: 'Body Double & Focus Guardian',
    tagline: 'Virtual company for the tasks you can\'t start alone.',
    description: 'A body-doubling and focus-session tool — set a task, run a timed session, and get the quiet sense of company that makes starting possible, without needing an actual person on a call.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'coming-soon',
    image: '/images/products/focus-guardian-01.jpg',
    features: [
      'Body-doubling focus sessions',
      'Task-based timer',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Body Double & Focus Guardian — Virtual Body-Doubling App',
    seoDescription: 'A downloadable body-doubling and focus session app for ADHD and AuDHD brains. Offline, no subscription.',
  },

  {
    id: 'exam-revision-sprint-timer',
    slug: 'exam-revision-sprint-timer',
    name: 'Exam Revision Sprint Timer',
    tagline: 'Focused revision sprints, built for brains that need the structure.',
    description: 'A sprint-based revision timer for exam prep — short focused bursts with real breaks, built for brains that burn out on generic Pomodoro apps that don\'t account for how studying actually feels.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'adhd-neurodivergent',
    categoryLabel: 'AuDHD & Neurodivergent',
    categorySlug: 'adhd-neurodivergent',
    status: 'coming-soon',
    image: '/images/products/exam-revision-timer-01.jpg',
    features: [
      'Sprint-based revision timer',
      'Structured break cycles',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Exam Revision Sprint Timer — Focused Study Timer App',
    seoDescription: 'A downloadable exam revision sprint timer built for ADHD and AuDHD brains. Offline, no subscription.',
  },

  {
    id: 'decision-spinner',
    slug: 'decision-spinner',
    name: 'Decision Spinner',
    tagline: 'When "I don\'t know, what do you want" has gone on long enough.',
    description: 'A quick decision-making tool for the small choices that eat up disproportionate energy — load your options, spin, and actually move on with your day.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/decision-spinner-01.jpg',
    features: [
      'Custom option lists',
      'Quick-spin decision tool',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Decision Spinner — Quick Decision-Making App',
    seoDescription: 'A downloadable decision-making spinner for everyday choices. Offline, no subscription.',
  },

  {
    id: 'fuel-log',
    slug: 'fuel-log',
    name: 'Fuel Log',
    tagline: 'Track every fill-up, every cost, every mile per gallon.',
    description: 'A simple fuel tracking app — log fill-ups, costs, and consumption over time, so you actually know what your car is costing you instead of guessing.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'productivity-daily-life',
    categoryLabel: 'Productivity & Daily Life',
    categorySlug: 'productivity-daily-life',
    status: 'coming-soon',
    image: '/images/products/fuel-log-01.jpg',
    features: [
      'Fill-up and cost logging',
      'Consumption tracking over time',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Fuel Log — Fuel Cost & Consumption Tracker',
    seoDescription: 'A downloadable fuel tracking app for logging fill-ups, costs, and consumption. Offline, no subscription.',
  },

  {
    id: 'business-idea-validator',
    slug: 'business-idea-validator',
    name: 'Business Idea Validator',
    tagline: 'Stress-test the idea before you spend a penny building it.',
    description: 'A structured validation tool for a new business idea — work through the real questions about market, cost, and demand before you commit time and money to building it.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'business-tools',
    categoryLabel: 'Business Tools',
    categorySlug: 'business-tools',
    status: 'coming-soon',
    image: '/images/products/business-idea-validator-01.jpg',
    features: [
      'Structured idea validation framework',
      'Market and demand prompts',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Business Idea Validator — Validate Before You Build',
    seoDescription: 'A downloadable business idea validation tool. Offline, no subscription.',
  },

  {
    id: 'business-launch-checklist',
    slug: 'business-launch-checklist',
    name: 'Business Launch Checklist',
    tagline: 'Everything you actually need before you open your doors.',
    description: 'A complete launch checklist for a new business — the legal, financial, and operational steps that are easy to miss when you\'re moving fast, tracked in one place.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'business-tools',
    categoryLabel: 'Business Tools',
    categorySlug: 'business-tools',
    status: 'coming-soon',
    image: '/images/products/business-launch-checklist-01.jpg',
    features: [
      'Full pre-launch checklist',
      'Progress tracking',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Business Launch Checklist — Pre-Launch Task Tracker',
    seoDescription: 'A downloadable business launch checklist covering legal, financial, and operational steps. Offline, no subscription.',
  },

  {
    id: 'client-onboarding-kit',
    slug: 'client-onboarding-kit',
    name: 'Client Onboarding Kit',
    tagline: 'A repeatable onboarding process, instead of winging it every time.',
    description: 'A client onboarding tracker built for service businesses — the same solid first impression and information-gathering process, every single time, without reinventing it per client.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'business-tools',
    categoryLabel: 'Business Tools',
    categorySlug: 'business-tools',
    status: 'coming-soon',
    image: '/images/products/client-onboarding-kit-01.jpg',
    features: [
      'Repeatable onboarding workflow',
      'Client information tracking',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Client Onboarding Kit — Repeatable Client Onboarding App',
    seoDescription: 'A downloadable client onboarding tracker for service businesses. Offline, no subscription.',
  },

  {
    id: 'freelance-business-starter',
    slug: 'freelance-business-starter',
    name: 'Freelance Business Starter',
    tagline: 'The business admin side of freelancing, actually sorted.',
    description: 'A starter kit for the operational side of freelancing — the setup, tracking, and admin structure that most freelancers put off until it becomes a problem.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'business-tools',
    categoryLabel: 'Business Tools',
    categorySlug: 'business-tools',
    status: 'coming-soon',
    image: '/images/products/freelance-business-starter-01.jpg',
    features: [
      'Freelance business setup tracker',
      'Operational admin structure',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Freelance Business Starter — Freelance Admin & Setup App',
    seoDescription: 'A downloadable freelance business starter kit for setup and admin tracking. Offline, no subscription.',
  },

  {
    id: 'pricing-calculator',
    slug: 'pricing-calculator',
    name: 'Pricing Calculator',
    tagline: 'Price your work so it actually covers what it costs you.',
    description: 'A pricing calculator built for service businesses — work backward from your real costs and target income to a rate that actually holds up, instead of guessing a number that feels right.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'business-tools',
    categoryLabel: 'Business Tools',
    categorySlug: 'business-tools',
    status: 'coming-soon',
    image: '/images/products/pricing-calculator-01.jpg',
    features: [
      'Cost-based pricing calculator',
      'Target income modelling',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Pricing Calculator — Service Business Pricing Tool',
    seoDescription: 'A downloadable pricing calculator for service businesses to price work against real costs. Offline, no subscription.',
  },

  {
    id: 'simple-bookkeeping',
    slug: 'simple-bookkeeping',
    name: 'Simple Bookkeeping',
    tagline: 'Income, expenses, and where you actually stand — in one place.',
    description: 'A straightforward bookkeeping tool for small and solo businesses — track income and expenses and see where you actually stand, without learning accounting software you\'ll never fully use.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'business-tools',
    categoryLabel: 'Business Tools',
    categorySlug: 'business-tools',
    status: 'coming-soon',
    image: '/images/products/simple-bookkeeping-01.jpg',
    features: [
      'Income and expense tracking',
      'Running totals',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Simple Bookkeeping — Income & Expense Tracker for Small Business',
    seoDescription: 'A downloadable simple bookkeeping tool for small and solo businesses. Offline, no subscription.',
  },

  {
    id: 'the-empress',
    slug: 'the-empress-full-life-planner',
    name: 'The Empress — Full Life Planner',
    tagline: 'A complete life planner, in one jewel-toned offline app.',
    description: 'A 7-room full life planner covering every area that needs real structure — built for people who\'ve outgrown a single-purpose tracker and want everything living in one place.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'life-planning',
    categoryLabel: 'Life Planning',
    categorySlug: 'life-planning',
    status: 'coming-soon',
    image: '/images/products/the-empress-01.jpg',
    badge: 'Premium',
    features: [
      'Seven planning rooms in one app',
      'Jewel-toned locked visual design',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'The Empress — Full Life Planner App',
    seoDescription: 'A downloadable 7-room full life planner. Offline, no subscription, yours forever.',
  },

  {
    id: 'bramble-and-ink',
    slug: 'bramble-and-ink-wildwood-almanac',
    name: 'Bramble & Ink — A Wildwood Almanac',
    tagline: 'The same full life planner, reimagined for a grungy fairycore world.',
    description: 'A grungy-fairycore reskin of The Empress — the same complete life-planning structure, wrapped in a nightshade-and-parchment aesthetic for a completely different mood.',
    price: 0,
    priceId: '',
    productType: 'app',
    category: 'life-planning',
    categoryLabel: 'Life Planning',
    categorySlug: 'life-planning',
    status: 'coming-soon',
    image: '/images/products/bramble-and-ink-01.jpg',
    badge: 'Premium',
    features: [
      'Seven planning rooms in one app',
      'Grungy-fairycore locked visual design',
      'Works fully offline',
      'No account, no subscription',
    ],
    seoTitle: 'Bramble & Ink — A Wildwood Almanac Life Planner',
    seoDescription: 'A downloadable grungy-fairycore full life planner. Offline, no subscription, yours forever.',
  },

  // ── SITEFILL TEMPLATES ────────────────────────────────────────────────────

  {
    id: 'coach',
    slug: 'life-coach-website-template',
    name: 'Life Coach',
    tagline: 'Convert visitors into booked clients.',
    description: 'Built for coaches and consultants who want a site that sells. Clear messaging, trust signals, and a booking-ready layout — all editable without touching a line of code.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_COACH || '',
    productType: 'template',
    category: 'coaches',
    categoryLabel: 'Coach',
    categorySlug: 'coaches',
    status: 'live',
    image: '/images/products/coach-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Services & packages section',
      'Testimonials & social proof block',
      'Booking / enquiry CTA',
      'Newsletter opt-in',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Life Coach Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'A premium one-page life coach website template with a built-in editor. Edit live, download, publish anywhere. No code, no subscription.',
  },

  {
    id: 'freelancer',
    slug: 'freelancer-website-template',
    name: 'Freelancer',
    tagline: 'Land more clients with a site that works as hard as you do.',
    description: 'Everything a freelancer needs — portfolio, services, testimonials, and contact. Clean, fast, and instantly editable with the SiteFill™ editor.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_FREELANCER || '',
    productType: 'template',
    category: 'freelancers',
    categoryLabel: 'Freelancer',
    categorySlug: 'freelancers',
    status: 'live',
    image: '/images/products/freelancer-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Portfolio section with image uploads',
      'Services, testimonials & contact',
      'Rates / packages section',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Freelancer Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'A premium one-page freelancer website template. Edit live in the browser, download, publish anywhere. No code needed.',
  },

  {
    id: 'novelist',
    slug: 'author-website-template',
    name: 'Author',
    tagline: 'For writers who mean business.',
    description: 'Showcase your books, events, press, and newsletter in one elegant page. Built for fiction and non-fiction authors who want a proper platform.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_AUTHOR || '',
    productType: 'template',
    category: 'authors',
    categoryLabel: 'Author',
    categorySlug: 'authors',
    status: 'live',
    image: '/images/products/novelist-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Books, events & press sections',
      'Newsletter signup',
      'Reader-first layout',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Author Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'A premium one-page author website template. Books, events, press, and newsletter — all editable live. No code, no subscription.',
  },

  {
    id: 'podcast',
    slug: 'podcast-website-template',
    name: 'Podcast',
    tagline: 'Your show deserves its own stage.',
    description: 'A full podcast home with episode listings, platform links, and a host bio. Stand out from the sea of generic podcast pages.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_PODCAST || '',
    productType: 'template',
    category: 'podcasters',
    categoryLabel: 'Podcaster',
    categorySlug: 'podcasters',
    status: 'live',
    image: '/images/products/podcast-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Episode listing section',
      'Listen on Spotify / Apple links',
      'Host bio & guest section',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Podcast Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'A premium one-page podcast website template. Episodes, platform links, host bio — all editable live. No code, no subscription.',
  },

  {
    id: 'shop',
    slug: 'shop-website-template',
    name: 'Shop & Artisan',
    tagline: 'Sell your work beautifully.',
    description: 'A handcrafted-aesthetic store template for makers, artists, and independent sellers. Warm, editorial, and conversion-focused.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_SHOP || '',
    productType: 'template',
    category: 'shops',
    categoryLabel: 'Shop',
    categorySlug: 'shops',
    status: 'live',
    image: '/images/products/shop-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Product showcase sections',
      'About the maker section',
      'Testimonials & social proof',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Shop & Artisan Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'A premium one-page shop template for makers and artisans. Editable live in the browser, no code, no subscription.',
  },

  {
    id: 'pt',
    slug: 'personal-trainer-website-template',
    name: 'Personal Trainer',
    tagline: 'Get more clients. Look the part.',
    description: 'Bold, high-energy design built for PTs and fitness coaches. Services, transformations, testimonials, and booking — all in one page.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_PT || '',
    productType: 'template',
    category: 'fitness',
    categoryLabel: 'Personal Trainer',
    categorySlug: 'fitness',
    status: 'live',
    image: '/images/products/pt-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Services & pricing section',
      'Transformation gallery',
      'Booking / enquiry section',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Personal Trainer Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'A premium one-page personal trainer website template. Services, testimonials, booking — editable live. No code, no subscription.',
  },

  {
    id: 'pt-premium',
    slug: 'personal-trainer-premium-template',
    name: 'Personal Trainer Premium',
    tagline: 'The full package for serious fitness brands.',
    description: 'Everything in the standard PT template, plus premium sections: video hero, full testimonial slider, FAQs, and an expanded transformation showcase.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_PT_PREMIUM || '',
    productType: 'template',
    category: 'fitness',
    categoryLabel: 'Personal Trainer',
    categorySlug: 'fitness',
    status: 'live',
    image: '/images/products/pt-premium-01.jpg',
    mockupCount: 7,
    badge: 'Premium',
    features: [
      'All standard PT features',
      'Video hero section',
      'Full testimonial slider',
      'Expanded transformation gallery',
      'FAQ section',
    ],
    seoTitle: 'Personal Trainer Premium Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'The premium personal trainer website template. Video hero, testimonial slider, FAQs, and more. No code, no subscription.',
  },

  {
    id: 'author-premium',
    slug: 'author-premium-template',
    name: 'Author Premium',
    tagline: 'The complete author web presence.',
    description: 'The full author suite — books, events, press, newsletter, podcast, and a dedicated media kit section. For authors building a serious platform.',
    price: 0,
    priceId: process.env.NEXT_PUBLIC_PRICE_AUTHOR_PREMIUM || '',
    productType: 'template',
    category: 'authors',
    categoryLabel: 'Author',
    categorySlug: 'authors',
    status: 'live',
    image: '/images/products/author-premium-01.jpg',
    mockupCount: 7,
    badge: 'Premium',
    features: [
      'All standard Author features',
      'Podcast / interview section',
      'Media kit section',
      'Extended press & reviews',
      'Speaking engagements section',
    ],
    seoTitle: 'Author Premium Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'The premium author website template. Books, events, media kit, podcast section — all editable live. No code, no subscription.',
  },

  {
    id: 'speaker',
    slug: 'speaker-website-template',
    name: 'Speaker',
    tagline: 'Colourful, bold, neo-brutalist. For the speaker whose energy is the pitch.',
    description: 'A maximalist keynote speaker website — topics, showreel, press, and a booking CTA, built for speakers who want their site as loud and unmissable as their stage presence.',
    price: 0,
    priceId: '',
    productType: 'template',
    category: 'speakers',
    categoryLabel: 'Speaker',
    categorySlug: 'speakers',
    status: 'coming-soon',
    image: '/images/products/speaker-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Topics & showreel sections',
      'Press section',
      'Booking / enquiry CTA',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Keynote Speaker Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'A bold, maximalist keynote speaker website template with a built-in editor. Edit live, download, publish anywhere. No code, no subscription.',
  },

  {
    id: 'author-press-kit-velvetheat',
    slug: 'author-press-kit-velvetheat',
    name: 'Author Press Kit (VelvetHeat)',
    tagline: 'A press kit built for authors who write the books people whisper about.',
    description: 'A moody, romantic one-page press kit for authors — bio, book highlights, and press-ready details in a VelvetHeat aesthetic built to stand out from the standard author template.',
    price: 0,
    priceId: '',
    productType: 'template',
    category: 'authors',
    categoryLabel: 'Author',
    categorySlug: 'authors',
    status: 'coming-soon',
    image: '/images/products/author-press-kit-velvetheat-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Author bio & hero section',
      'Book highlights section',
      'Press-ready contact details',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Author Press Kit Website Template (VelvetHeat) — SiteFill™ by KiTee Studio',
    seoDescription: 'A moody, romantic author press kit website template with a built-in editor. Edit live, download, publish anywhere. No code, no subscription.',
  },

  {
    id: 'author-website-velvetheat',
    slug: 'author-website-velvetheat-template',
    name: 'Author (VelvetHeat)',
    tagline: 'A darker, moodier author site for a different kind of story.',
    description: 'An alternate author website design in the VelvetHeat aesthetic — books, about, process, and events — for authors whose brand doesn\'t fit the standard Author template\'s look.',
    price: 0,
    priceId: '',
    productType: 'template',
    category: 'authors',
    categoryLabel: 'Author',
    categorySlug: 'authors',
    status: 'coming-soon',
    image: '/images/products/author-website-velvetheat-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Books section',
      'About & writing process sections',
      'Events section',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Author Website Template (VelvetHeat) — SiteFill™ by KiTee Studio',
    seoDescription: 'A moody, alternate-aesthetic author website template with a built-in editor. Edit live, download, publish anywhere. No code, no subscription.',
  },

  {
    id: 'va-template',
    slug: 'virtual-assistant-website-template',
    name: 'Virtual Assistant',
    tagline: 'A site that shows exactly what you take off someone\'s plate.',
    description: 'A clean, trust-first website template for virtual assistants — services, process, and a clear path to booking, built for VAs who want to look as organised as the work they do.',
    price: 0,
    priceId: '',
    productType: 'template',
    category: 'virtual-assistants',
    categoryLabel: 'Virtual Assistant',
    categorySlug: 'virtual-assistants',
    status: 'coming-soon',
    image: '/images/products/va-template-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Services & process sections',
      'Booking / enquiry CTA',
      'Testimonials & social proof',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Virtual Assistant Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'A premium one-page virtual assistant website template with a built-in editor. Edit live, download, publish anywhere. No code, no subscription.',
  },

  {
    id: 'speaker-press-kit',
    slug: 'speaker-press-kit-template',
    name: 'Speaker Press Kit',
    tagline: 'One page, everything an event organiser needs to say yes.',
    description: 'A one-page speaker press kit — bio, topics, and booking details in a format built for the person deciding whether to book you, not for browsing.',
    price: 0,
    priceId: '',
    productType: 'template',
    category: 'speakers',
    categoryLabel: 'Speaker',
    categorySlug: 'speakers',
    status: 'coming-soon',
    image: '/images/products/speaker-press-kit-01.jpg',
    mockupCount: 7,
    features: [
      'SiteFill™ visual editor built in',
      'Speaker bio & topics section',
      'Booking-ready contact details',
      'One-click download — no hosting needed',
    ],
    seoTitle: 'Speaker Press Kit Website Template — SiteFill™ by KiTee Studio',
    seoDescription: 'A one-page speaker press kit template with a built-in editor. Edit live, download, publish anywhere. No code, no subscription.',
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────
export function getProductBySlug(slug: string) {
  return PRODUCTS.find(p => p.slug === slug);
}

export function getProductsByType(type: ProductType) {
  return PRODUCTS.filter(p => p.productType === type);
}

export function getAppsByCategory(category: AppCategory) {
  return PRODUCTS.filter(p => p.productType === 'app' && p.category === category);
}

export function getLiveProducts() {
  return PRODUCTS.filter(p => p.status === 'live');
}

